[package]
name = "reverse_rs"
version = "0.1.0"
authors = ["Mikail Khan <mikail.khan45@gmail.com>"]
edition = "2018"

[dependencies]
criterion = "0.2"

[[bench]]
name = "my_benchmark"
harness = false
